Repository microsoft/vscode-isort, pull requests merged in 2022-05, with the labels that each got.

#24 Add GIF for isort
  README.md
  images/vscode-isort.gif
Labels: skip news

#31 Restarting should use the same python
  .github/workflows/pr-labels.yml
  src/common/formatLS.ts
Labels: bug, skip news

#36 Update labels
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/issue-labels.yml
  .github/workflows/pr-labels.yml
Labels: debt, skip news

#43 Update packages
  .github/dependabot.yml
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt, skip news

#44 Handle FileSkipped scenarios.
  bundled/formatter/format_server.py
  noxfile.py
Labels: bug, skip news

#47 Update packages
  package-lock.json
  package.json
  src/test/python_tests/requirements.txt
Labels: debt, skip news
