Repository microsoft/vscode-isort, pull requests merged in 2022-08, with the labels that each got.

#95 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt, skip news

#98 Update extension to use the latest extension template.
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .vscode/launch.json
  .vscode/settings.json
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/formatter/format_server.py
  bundled/formatter/runner.py
  bundled/tool/__init__.py
  bundled/tool/_debug_server.py
  bundled/tool/jsonrpc.py
  bundled/tool/runner.py
  bundled/tool/server.py
  bundled/tool/utils.py
  noxfile.py
  package-lock.json
  package.json
  package.nls.json
  src/common/constants.ts
  src/common/log/fileLogger.ts
  src/common/log/logging.ts
  src/common/log/outputChannelLogger.ts
  src/common/log/types.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/setup.ts
  src/common/utilities.ts
  src/extension.ts
  src/setupNLS.ts
  src/test/python_tests/lsp_test_client/defaults.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_path_specialization.py
  src/test/python_tests/test_sort.py
  webpack.config.js
Labels: debt

#102 Adds codereview chat action
  .github/workflows/pr-chat.yml
Labels: no-changelog

#104 Fix line endings before formatting.
  bundled/tool/server.py
  src/test/python_tests/test_sort.py
Labels: bug

#105 Update packages.
  noxfile.py
  package-lock.json
  package.json
  requirements.txt
Labels: debt
