Repository microsoft/vscode-isort, pull requests merged in 2022-06, with the labels that each got.

#55 Update packages
  package-lock.json
  package.json
Labels: debt, skip news

#48 Add Trailing Commas in json Example
  README.md
Labels: debt, news

#57 Fix for path duplication.
  bundled/formatter/format_server.py
Labels: bug, news

#63 Update packages
  package-lock.json
  package.json
Labels: debt, skip news

#65 Ensure '-' is the first argument.
  bundled/formatter/format_server.py
Labels: bug, skip news

#67 Ensure nothing is returned if stdout is empty.
  bundled/formatter/format_server.py
Labels: bug, skip news

#70 Update main version post release.
  package-lock.json
  package.json
Labels: debt, skip news

#76 Update packages.
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: debt, skip news
