Repository microsoft/vscode-isort, pull requests merged in 2022-11, with the labels that each got.

#135 Update packages and extension version
  package-lock.json
  package.json
  src/test/python_tests/requirements.txt
Labels: no-changelog

#136 Update version to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#123 Use test runner from VS Code for tests.
  .github/workflows/pr-check.yml
  .vscode/launch.json
  bundled/tool/server.py
  package-lock.json
  package.json
  requirements.txt
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
  src/test/ts_tests/index.ts
  src/test/ts_tests/runTest.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
  test-results.xml
Labels: debt

#145 Change default severity for `isort` issues to warning.
  bundled/tool/server.py
  package.json
  src/common/settings.ts
  src/test/python_tests/test_sort.py
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: bug

#146 Fix for unable to read `map` issue with CodeActions
  bundled/tool/server.py
  src/test/python_tests/test_sort.py
Labels: bug

#149 Reduce severity of import organization to hints
  bundled/tool/server.py
  package.json
  src/common/settings.ts
  src/test/python_tests/test_sort.py
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: bug

#150 Update extension version for release.
  package-lock.json
  package.json
Labels: no-changelog

#151 Update version to next pre-release.
  package-lock.json
  package.json
Labels: no-changelog

#154 Show code actions only when there are issues reported
  bundled/tool/server.py
Labels: bug

#156 Re-order settings in package.json
  package.json
Labels: debt

#155 Skip running organize import on interactive window
  bundled/tool/server.py
Labels: bug

#159 Bump the version number for a `2022.8.0` release
  package-lock.json
  package.json
Labels: no-changelog

#162 Bump version to `2022.9.0-dev`
  package-lock.json
  package.json
Labels: no-changelog

#164 Fix cli flag in example.
  README.md
Labels: documentation, no-changelog

#167 Remove PR Chat
  .github/workflows/pr-chat.yml
Labels: debt
