Repository microsoft/vscode-isort, pull requests merged in 2022-10, with the labels that each got.

#119 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#120 Update to use latest python environment APIs
  package-lock.json
  package.json
  src/common/python.ts
Labels: feature-request

#122 Support legacy settings from python extension (temporarily).
  src/common/settings.ts
Labels: feature-request

#124 Fix bug with settings and error.
  bundled/tool/server.py
  src/common/settings.ts
Labels: no-changelog

#125 Add `isort.check` setting
  bundled/tool/server.py
  package.json
  package.nls.json
  src/common/settings.ts
  src/test/python_tests/test_path_specialization.py
  src/test/python_tests/test_sort.py
Labels: feature-request

#126 Set default for `isort.check` to false
  bundled/tool/server.py
  package.json
  src/common/settings.ts
  src/test/python_tests/test_sort.py
Labels: feature-request

#127 Update CHANGELOG.md
  CHANGELOG.md
Labels: no-changelog

#130 Fix for pydantic crash on Python 3.11
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  noxfile.py
  requirements.txt
Labels: bug

#133 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
