Repository microsoft/vscode-isort, pull requests merged in 2023-06, with the labels that each got.

#286 Bug fixes and package updates from extension template
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/log/fileLogger.ts
  src/common/log/logging.ts
  src/common/log/outputChannelLogger.ts
  src/common/log/types.ts
  src/common/logging.ts
  src/common/python.ts
  src/common/runner.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/setup.ts
  src/common/sortImports.ts
  src/common/status.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: bug

#287 Update logging details for `isort`
  README.md
  bundled/tool/lsp_server.py
Labels: debt

#290 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#293 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug
