Repository microsoft/vscode-isort, pull requests merged in 2023-02, with the labels that each got.

#221 Fix linting build failure
  bundled/tool/lsp_server.py
Labels: no-changelog

#222 Migrate to `python-lsp-jsonrpc`
  .vscodeignore
  README.md
  requirements.txt
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#213 Use Dependabot on local Actions
  .github/dependabot.yml
Labels: debt

#224 Ensure LSP server is shutdown on extension exit
  bundled/tool/lsp_server.py
  package-lock.json
  src/extension.ts
Labels: bug

#225 Update packages
  package-lock.json
  package.json
Labels: no-changelog

#226 Add logging when legacy settings are used.
  src/common/settings.ts
Labels: bug

#239 Fix path bug and crlf issue on windows.
  src/common/runner.ts
Labels: bug

#246 Ensure that global settings are passed to the server.
  bundled/tool/lsp_server.py
  src/common/server.ts
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/utils.py
Labels: bug
