Repository microsoft/vscode-isort, pull requests merged in 2023-01, with the labels that each got.

#174 Fix mistype on README
  README.md
Labels: debt

#201 Fix for code action error using `isort` with `ruff`
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  bundled/tool/server.py
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_sort.py
  src/test/ts_tests/runTest.ts
Labels: bug

#202 Fix build issues on Azure.
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
  requirements.txt
Labels: no-changelog

#203 Update localization
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
  src/extension.ts
  src/setupNLS.ts
  webpack.config.js
Labels: debt

#207 Support for `isort` in server less mode
  .vscode/settings.json
  README.md
  bundled/tool/_debug_server.py
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  bundled/tool/script_runner.py
  package.json
  package.nls.json
  src/common/constants.ts
  src/common/runner.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/sortImports.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/lsp_test_client/session.py
Labels: feature-request

#208 Fix typos in settings descriptions
  package.nls.json
Labels: bug

#210 Ensure serverless mode works with path set.
  bundled/tool/script_runner.py
  src/common/runner.ts
Labels: no-changelog

#214 Update version for pre-release
  package.json
Labels: no-changelog
