Repository microsoft/vscode-isort, pull requests merged in 2023-11, with the labels that each got.

#338 Upgrade to Python 3.8 as minimal required version.
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#332 Updated packages for extension
  package-lock.json
  package.json
Labels: debt, ghc-osd

#345 Tweak build and checks
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
Labels: no-changelog

#348 Update README
  README.md
  package.json
  package.nls.json
Labels: documentation, debt
